### ISSUE TITLE
Not an issue.. Just wanted to add a functionality if someone need.

### ISSUE THREAD

**Issue by Danish12** [renvrant/conditionize.js#10]
In case you want a form field to be shown were it shall be depended on two filed. 
Like show C only when A - Yes and B - Yes has been selected. 

[Multi field dependent Show HIde.txt](https://github.com/renvrant/conditionize.js/files/1135282/Multi.field.dependent.Show.HIde.txt)
In that case use the Attached Demo. Save it as an HTML file.

**Comment by rguliev** [comment]
Hi,
Please take a look at flexible version of the plugin: [conditionize.flexible.jquery.js](https://github.com/rguliev/conditionize.js/tree/improvements).  
For your case it must look like this:
```html
<div class="conditional" data-condition="foo == 'bar1' || foo == 'bar2'">...</div>
```
or
```html
<div class="conditional" data-condition="['bar1','bar2'].includes(foo)">...</div>
```
The rest is the same.
