### ISSUE TITLE
data-condition isn't satisfied but field is shown

### ISSUE THREAD

**Issue by MaRVaOnDzZ** [renvrant/conditionize.js#14]
Hi everyone,

I'm getting a little issue with `conditionize.flexible.jquery.js`

I have a field named `email`, and other field below with `data-condition=email != ''`
This works fine but I have a JS function which remove invalid values from email, so if I put an invalid value in email field, the other field is shown but the email field is `''`.

I think the condition is not checked again after JS function is executed.

Someone knows how to solve this?

**Comment by rguliev** [comment]
Hello,
I would recommend to try trigger change at the end of your `JS function which remove invalid values from email`, i.e. try this
```
myEmailValidatorFunction(){
// There your validation
$('#my_email_input').trigger('change');
}
```

**Comment by rguliev** [comment]
@MaRVaOnDzZ, Did that work for you?
I'm closing the issue since it seems like problem is out of the `conditionize.flexible.jquery.js`.
