### ISSUE TITLE
Multiple Values don't work with Flexible.

### ISSUE THREAD

**Issue by CodeCurosity** [renvrant/conditionize.js#23]
`data-condition="#a1 < 5 && #a2 > 25` only the 2nd condition works.

`data-condition="#a1 == love && #a1 == magic` none of them work.

I even tried just one text condition to show, nothing seems to work.

When i tried typing love it shows error in console : `$('#a1').val()==love`

`Uncaught ReferenceError: love is not defined`

**Comment by rguliev** [comment]
You should put `love` in quotes. Like `"data-condition="#a1 == 'love' && #a1 == 'magic'"`. Otherwise javascript thinks that it is a variable. `love is not defined` means "Sorry, I see no variable called love".

**Comment by UsmanShahzad** [comment]
I actually did put it in quotes and it may not show the error but it didnt work, i will try again tomorrow, thanks.

**Comment by rguliev** [comment]
Ok. If it will not work, please provide the whole non-working example with the context. I mean html code with inputs and etc.

**Comment by UsmanShahzad** [comment]
Ok yes it was a cache issue, i reset it and it worked but multiple options still don't work

If i add two options even the first one doesn't work.

data-condition="#a1 == 'love' && #a1 == 'magic'

**Comment by rguliev** [comment]
Just replace `&&` with `||`. Otherwise you are waiting for a string to be both ‘love’ AND ‘magic’ at the same time.

**Comment by UsmanShahzad** [comment]
Great, Thanks :+1:

**Comment by rguliev** [comment]
Welcome:)
> Is it not possible to set it like this data-condition = "#a1 == 'love || magic'" ?
That will require creating of own syntax which is not that flexible. You can use javascript functions inside conditions like `data-condition = "['love, 'magic'].includes(#a1)"`. But be careful with browser support: https://caniuse.com/#search=includes
