### ISSUE TITLE
conditionize.flexible.js doens't seem to work with checkboxes

### ISSUE THREAD

**Issue by IsmailM** [renvrant/conditionize.js#28]
Demonstrated here: [codepen.io/ismailm___/pen/QzEjgj?editors=1010](https://codepen.io/ismailm___/pen/QzEjgj?editors=1010) (i.e. using the JS in the current master branch).

The issue is that checkboxes can hold multiple values - and as such `$(input_name:checked).val()` will always be the first checked value...

So, need to decide on what is the right behaviour:
	- Should the conditional be true as long as the value is included in the checked boxes.
    - Or should the expected value be the only checked box?

It should be a relatively easy fix once the above is decided...

**Comment by rguliev** [comment]
Kinda redundancy in our discussions:)

> It should be a relatively easy fix once the above is decided...

It think it is not up to us to decide. It must be implemented in such a way allowing to choose between them. One solution, came to my mind, is to return an array of values(like `[1,2,3]`) if a selector returns more than one input. That will make a condition more flexible, i.e. one can choose: `my_favorite_books[] === [1]` or `mutivalue_checkbox.includes(1)`

**Comment by rguliev** [comment]
Sorry, it is kinda messy discussing similar things in many places. Let's keep everything in the initial issue: #18. I will rename it to something more relevant.
