### ISSUE TITLE
Show field when not empty

### ISSUE THREAD

**Issue by CodeCurosity** [renvrant/conditionize.js#30]
what would be the condition if i want to show the next field when the first field has some value in it e.g show field 2 when field 1 is not empty.

**Comment by rguliev** [comment]
Hi,
Have you tried something like `data-condition="#field1 != ''"`?

**Comment by CodeCurosity** [comment]
It works on your codepen but when i set this as an option in my application it throws error so i used this `data-condition="#field1 != [ ]"` and it worked just fine, thanks and btw are you working on that name [ ] and multiple checkboxes and radio button problem, i could really use that right now, thanks :)

**Comment by rguliev** [comment]
Hmm.. That is interesting. Can you show your code?
Haven't started yet. But I am planning to start the next week.
