### ISSUE TITLE
Any update on radio button with same name and [ ]

### ISSUE THREAD

**Issue by CodeCurosity** [renvrant/conditionize.js#32]
Any update on multiple inputs with same name e.g radio and also name with [ ]

**Comment by rguliev** [comment]
Hi,
Sorry for the delay. Unfortunately, I am a bit out of the schedule because of my main job. But I'm in progress and planning to finish until the end of the Jan.
I'm closing this issue because it's not actually an issue. You can just write a comment at the relevant issue.
