### ISSUE TITLE
Package manager

### ISSUE THREAD

**Issue by Recursivepaiste** [renvrant/conditionize.js#34]
Not sure if this is the right place but are there any plans for adding this to something like yarn or NPM in the future, if not is this something which could be done?

**Comment by rguliev** [comment]
Hi,
Right now I am moving conditionize.flexible to conditionize2 with some extensions and better testing. I am planning to add it to npm. But right now I am working on finishing conditionize2.js.

**Comment by Recursivepaiste** [comment]
Ok, thanks for the update. Sounds good.
