### ISSUE TITLE
Multiples forms

### ISSUE THREAD

**Issue by Mayccoll** [renvrant/conditionize.js#6]
Hi,
I'm making a landing page with multiple form but same fields. ¿There is a way to get the condition by some ```data-``` instead of ```name=""``` ? because  the requirement is i have to use the same name for the fields.

Here is the example of my problem:
http://codepen.io/anon/pen/gPVvGY

Thanks

**Comment by Ivanner** [comment]
I had the same issue and I just submitted a pull request. I modified the code to use id as selectors, allowing you to re-use the input names.
https://github.com/renvrant/conditionize.js/pull/8
